title: Jordi Solis
logo: Profile Picture.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  BI Analyst | SQL + Tableau | Data into Strategy
  <br><br>
  Hi there! I'm Jordi Solis, a business operations professional transitioning into business intelligence through data storytelling. This repository showcases my journey—from foundational concepts to complex analytical solutions.I'm continually sharpening my skills through daily practice and new challenges. Feel free to explore
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
