title: Jordi Solis
logo: Profile Picture.png
description: > # your text below (remove <br> elements if you don't need line breaks)
 "BI Analyst | SQL + Tableau | Turning data into strategy"
  <br><br>
"Hello! I'm Jordi Solis – a Business Intelligence professional with 7+ years in operational strategy and data-driven decision-making. As a former academic coach, I discovered that unlocking insights from data is even more rewarding than guiding students through complex curricula. Today, I bridge business needs and technical solutions by:

🔹 Transforming raw data into actionable narratives using SQL, Tableau, and Power BI
🔹 Optimizing processes (proven 15-25% efficiency gains in sales/retention)
🔹 Mentoring peers in data literacy (30% avg. performance improvement)

My toolkit:
SQL | Tableau | Power BI | Salesforce | Process Documentation

What fuels my work:
• Turning stakeholder questions into precise analytical frameworks
• Designing dashboards that make insights intuitive (not just "pretty")
• Balancing quantitative rigor with human context – because data without empathy is just noise

"Jordi has a strategic mind vital for initiatives and a natural empathy for people."
– Peter Marshall, Student Success Manager (Pearson)

Currently: Completed my Business Intelligence Certification (TripleTen, 2025) while driving enrollment analytics at UMGC – where I recently exceeded expectations.

Let's connect if you:

Value clear communication of complex data

Believe great analytics solves business and human challenges

Want to explore my SQL portfolio or Tableau work

P.S. My secret weapon: Spanish espresso ☕ and relentless curiosity."
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
